General Instructions:
- By array, I mean numpy array
- By matrix, I mean a numpy array of 2 dimensions

### 1
Write a function to create and return an integer array of shape (5, 2) from a range between 100 to 200 (including 100, excluding 200) such that the difference between consecutive elements is 10.

In [ ]:
def create_integer_array():
  ### Your Code Here
  import numpy as np
  x = np.arange(100,200,10).reshape(5,2)
  return(x)


### 2
Given a numpy array ```a```, of shape ```(m, n)``` m>=3, n>=3. Write a function to return an array consisting of the elements in 3rd column of ```a``` <br>
Eg., Suppose
``` 
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]    
```
Then 
```
column_3(a) -> [3 6 9]
```

In [ ]:
def column_3(a):
  ### Your Code here  
  import numpy as np
  return (a[:,2])



### 3
Write a function which does the following. Given a numpy array $a$ of shape (m, n), index $i$ and an array $b$ of shape (m, ). Replace the $i_{th}$ column of $a$ with the array $b$  
Eg., Suppose
```
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]
b = [30, 60, 90]

```    
Then,
```
replace_col(a, 2, b) -> [[1 2 30]
                         [4 5 60]
                         [7 8 90]]
```

In [ ]:
def replace_col(a, i, b):
  ### Your Code Here
  import numpy as np
  a[:,i] = b
  print (a)



[[ 1  2 30]
 [ 4  5 60]
 [ 7  8 90]]


### 4
Write a function which does the following. Given a numpy array $a$ of shape (m, n) and indices $i$, $j$. Return a numpy array which swaps the columns $i$ and $j$ of $a$
Eg., Suppose
```
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]

swap_cols(a, 0, 2) -> [[3 2 1]
                       [6 5 4]
                       [9 8 7]]
```

In [ ]:
def swap_cols(a, i, j):
  ### Your Code Here
  import numpy as np
  a[:,(i,j)] = a[:,(j,i)]
  return(a)
    

## 5

There are various equivalent ways to define the determinant of a square matrix A, i.e. one with the same number of rows and columns. Perhaps the simplest way to express the determinant is by considering the elements in the top row and the respective minors; starting at the left, multiply the element by the minor, then subtract the product of the next element and its minor, and alternate adding and subtracting such products until all elements in the top row have been exhausted. For example, here is the result for a 4 × 4 matrix: <br>

<img src = "https://drive.google.com/uc?id=1TTljfFZAnOvqgAOiOrv6r4DDRROD-Vph"> <br>

Also, for a 2x2 matrix, this is the formula - <br>
<img src = "https://drive.google.com/uc?id=1H3aFpr1guevWjz4F-XRUQ9eP5TfjVLwu"> <br>

###5.1 Minor
Write a function that does the following. 
Given a square matrix $A$ and an index $i$, find and return the sub-matrix that is the minor corresponding to element at index $i$ of the first row of $A$

In [ ]:
def minor(A, i):
  ### Write your code here
  if A.shape[0] == 1:
    return A

  else:
    return (np.delete(np.delete(A,i,1),0,0))
    
import numpy as np
minor(np.arange(9).reshape(3, 3), 2)

array([[3, 4],
       [6, 7]])

###5.2
Given a square matrix $A$, write a function that computes and return the determinant using the formula given above and the helper function that you have defined called ```minor```. <br>
(Do not use the functions to compute determinant which numpy provides built in)

In [ ]:
def determinant(A):
  ### Write your code here
  x = A.shape[0]
  if x == 1:
      return A[0]
    
  elif x == 2:
      return ((A[0,0] * A[1,1]) - (A[0,1] * A[1,0]))
    
  else:
      det = 0
      for i in range(x):
          det += (A[0,i] * ((-1) ** i) * determinant(minor(A,i)))
      
      return det


In [ ]:
a = np.random.random((3, 3))
determinant(a)

0.06031250111784091

In [ ]:
np.linalg.det(a)

0.06031250111784095